version: '3'
networks:
  link-generator:
services:
  app-admin:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql-link-generator
    networks:
      - link-generator

  mysql-link-generator:
    platform: linux/x86_64
    image: mariadb:10.6.16
    restart: unless-stopped
    tty: true
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: link-generator
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
    - dbdata:/var/lib/mysql
    networks:
      - link-generator
  php:
    build:
      context: .
      dockerfile: ./Docker/php/Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - link-generator

  composer:
    image: composer:latest
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php

  artisan:
    build:
      context: .
      dockerfile: ./Docker/php/Dockerfile
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql-link-generator
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - link-generator

  redis:
    image: redis:latest
    restart: always
    volumes:
      - cache:/data
    environment:
      - REDIS_PORT=6379
    networks:
      - link-generator

#Volumes
volumes:
  dbdata:
    driver: local
  cache:
    driver: local
